name: 'Build and install xcb-imdkit'

inputs:
  path:
    description: 'Path to source code'
    default: 'xcb-imdkit'
  install-prefix:
    description: 'Install prefix'
    default: 'out/install'

runs:
  using: composite
  steps:
    - name: Checkout
      if: github.repository != 'fcitx/xcb-imdkit'
      uses: actions/checkout@v4
      with:
        repository: fcitx/xcb-imdkit
        path: ${{ inputs.path }}
    - name: Configure
        run: |
          cmake -S "${{ inputs.path }}" -B "${{ inputs.path }}"/build -DCMAKE_INSTALL_PREFIX="${{ inputs.install-prefix }}"
    - name: Build
      run: |
        cmake --build "${{ inputs.path }}"/build
    - name: Install
      run: |
        cmake --install "${{ inputs.path }}"/build

