name: CI

on:
  push:
    branches:
      - master
    pull_requuest:
      branches:
        - master

jobs:
  check:
    name: Build and test
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm base-devel cmake extra-cmake-modules xcb-util xcb-util-keysyms
      - name: Check out
        uses: actions/checkout@v4
      - name: Init CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: c
      - name: Configure
        run: |
          cmake -S . -B build
      - name: Build
        run: |
          cmake --build build
      - name: Test
        run: |
          ctest --test-dir build
      - name: Install
        run: |
          cmake --install build
      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@v2
