name: CI

on:
  push:
    branches:
      - master
    pull_requuest:
      branches:
        - master

jobs:
  check:
    name: Build and test
    runs-on: ubuntu-latest
    container: archlinux:latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
        include:
          - compiler: gcc
            cxx_compiler: g++
          - compiler: clang
            cxx_compiler: clang++
    env:
      CC: ${{ matrix.compiler }}
      CXX: ${{ matrix.cxx_compiler }}
    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm base-devel clang cmake extra-cmake-modules xcb-util xcb-util-keysyms
      - name: Init CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: c
      - name: Build and Install
        uses: ./
      - name: Test
        run: |
          ctest --test-dir xcb-imdkit/build
      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@v2
